server:
  port: ${PORT_APP:8081}
  scheduler:
    fixedRateRead: 15000
    fixedRateWrite: 5000
  conversion:
    limit: 20
    bucketForPdf: ${TO_BUCKET_PDF:pdf}
    topicResponse: conversion-response

spring:
  datasource:
    url: ${URL_DB:jdbc:postgresql://postgres:5432/conversion}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
minio:
  url: ${URL:http://localhost:9000}
  access-key: ${ACCESS_KEY:jora}
  secret-key: ${SECRET_KEY:jora1234}

kafka:
  bootstrap-servers: ${URL_KAFKA:kafka:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: conversion
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.example.Zhora: DEBUG
    org:
      hibernate:
#        engine:
#          transaction: DEBUG
#        SQL: DEBUG
      apache:
        kafka:
          clients:
            NetworkClient=DEBUG:
